### PR TITLE
Final

### PR DESCRIPTION
**Pull request by azrielmacabante**
Assessment for Josiah Macabante

Inc but here are some that I did
html repor is in playwright-report folder

### CODE REVIEW

**Comment by christian-rivera95** [comment]
Thank you for your submission, we'll review it today.

**Comment by christian-rivera95** [comment]
@azrielmacabante Thank you for your submission. I appreciate your adherence to the Page Object Model (POM) structure, which significantly enhances the readability of your code.

However, I noticed that the test case for "Delete Kanban Card" is missing from your implementation. To complete the evaluation, please add this missing test case and submit a new commit as soon as possible. We are currently reviewing several candidates, so your prompt attention to this matter would be greatly appreciated.

**Comment by azrielmacabante** [comment]
Hello Chrisitan,

I will try to submit the code with the "Delete Kanban Card" test case by
the end of the day. Thank you very much!

Regards,
Josiah Macabante

**Comment by azrielmacabante** [comment]
hello @christian-rivera95 done adding the tc for "Delete Kanban Card". Thank you very much

**Pull request closed without merging**
